# Setup
title: WATCHHONG
tagline: Dev Blog
url: https://WATCHHONG.github.io
paginate: 1
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: PARK JIHONG
  url: https://github.com/WATCHHONG
  email: gihong0101@gmail.com

# Custom vars
version: 3.0.0

ga_analytics: G-XXXXXXXXXX
collections:
  posts:
    output: true
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: "PARK JIHONG"
      categories: ["Development", "Study"]
      tags: ["C Language", "Web", "SaaS", "AI"]

